title: hindustani classical collection 
description: We are trying to create a collection of records by various hindustani classical artists of past centuries 
theme: just-the-docs

url: https://amandeep511997.github.io/hindustani-classical-collection

back_to_top: true
back_to_top_text: "Back to top"


last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/amandeep511997/hindustani-classical-collection"
gh_edit_branch: "main" 
gh_edit_view_mode: "tree"

color_scheme: nil
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
